import type {
  ICategoryDetails,
  ICategoryListItem,
} from "../types/category.types";

const UNSPLASH = "https://images.unsplash.com";

// Same four photos the banner already ships, re-graded so each category reads
// as its own without pulling more images over the wire.
const photo = (id: string, grade = "") =>
  `${UNSPLASH}/${id}?auto=format&fit=crop&w=1600&q=80${grade}`;

const PIPES = "photo-1607472586893-edb57bdc0e39";
const PANEL = "photo-1621905251189-08b45d6a269e";
const BENCH = "photo-1558618666-fcd25c85cd64";
const TIMBER = "photo-1503387762-592deb58ef4e";

export const CATEGORY_LIST: ICategoryListItem[] = [
  {
    id: "cat-plumbing",
    name: "Plumbing",
    slug: "plumbing",
    description:
      "Leaks, blockages, geysers and bathroom fittings — handled by licensed plumbers who carry their own parts.",
    image: photo(PIPES),
    technicianCount: 86,
    serviceCount: 214,
    startingPrice: "450",
    averageRating: "4.87",
    totalReviews: 1290,
    popularServices: ["Leak repair", "Drain unblocking", "Geyser install"],
    isTrending: true,
  },
  {
    id: "cat-electrical",
    name: "Electrical",
    slug: "electrical",
    description:
      "Board upgrades, tripping circuits and new points, wired to code by technicians whose licences we check.",
    image: photo(PANEL),
    technicianCount: 74,
    serviceCount: 186,
    startingPrice: "500",
    averageRating: "4.91",
    totalReviews: 1104,
    popularServices: ["Wiring fault", "Board upgrade", "Light fitting"],
    isTrending: true,
  },
  {
    id: "cat-cooling",
    name: "AC & cooling",
    slug: "ac-cooling",
    description:
      "Servicing, gas top-ups and installs for split and window units, with a cleaned filter every visit.",
    image: photo(BENCH, "&bri=-18"),
    technicianCount: 61,
    serviceCount: 143,
    startingPrice: "800",
    averageRating: "4.79",
    totalReviews: 872,
    popularServices: ["AC servicing", "Gas refill", "New install"],
    isTrending: false,
  },
  {
    id: "cat-appliance",
    name: "Appliance repair",
    slug: "appliance-repair",
    description:
      "Fridges, ovens and washing machines diagnosed on site, with parts sourced before the second visit.",
    image: photo(BENCH, "&bri=-32&sat=-10"),
    technicianCount: 58,
    serviceCount: 167,
    startingPrice: "600",
    averageRating: "4.74",
    totalReviews: 940,
    popularServices: ["Fridge repair", "Washing machine", "Oven service"],
    isTrending: false,
  },
  {
    id: "cat-carpentry",
    name: "Carpentry",
    slug: "carpentry",
    description:
      "Doors, cabinets, mounts and fixtures measured, fitted and cleaned up before the technician leaves.",
    image: photo(TIMBER, "&bri=-28&sat=-10"),
    technicianCount: 47,
    serviceCount: 128,
    startingPrice: "700",
    averageRating: "4.83",
    totalReviews: 615,
    popularServices: ["Door repair", "Cabinet fitting", "TV mounting"],
    isTrending: false,
  },
  {
    id: "cat-painting",
    name: "Painting",
    slug: "painting",
    description:
      "Interior and exterior coats with surface prep, dust sheets down and the room put back as it was.",
    image: photo(TIMBER, "&sat=-40&bri=10"),
    technicianCount: 39,
    serviceCount: 96,
    startingPrice: "1200",
    averageRating: "4.68",
    totalReviews: 402,
    popularServices: ["Room repaint", "Exterior coat", "Damp patch fix"],
    isTrending: true,
  },
];

// Keyed by slug so a details route can look its own entry up directly.
export const CATEGORY_DETAILS: Record<string, ICategoryDetails> = {
  plumbing: {
    ...CATEGORY_LIST[0],
    coverImage: photo(PIPES, "&w=2400"),
    tagline: "Water where it should be, and nowhere else.",
    overview: [
      "Plumbing is the category customers reach for first, and the one where a wrong call costs the most. Every plumber listed here has cleared an ID check, submitted trade experience and had their first jobs reviewed before the profile went public.",
      "Rates are quoted before the visit and the payment sits in escrow until you confirm the leak has stopped. Parts are itemised on the invoice, so a ৳120 washer never turns into a ৳1,200 line.",
    ],
    completedJobs: 4180,
    responseMinutes: 42,
    priceRange: { min: "450", max: "2500" },
    commonIssues: [
      "Dripping taps and worn washers",
      "Blocked kitchen or bathroom drains",
      "Leaking pipe joints behind tiles",
      "Geyser not heating or leaking",
      "Low water pressure through the flat",
      "Toilet running or not flushing",
    ],
    topTechnicians: [
      {
        id: "tech-p1",
        name: "Karim Mia",
        avatar: null,
        professionalTitle: "Senior plumber",
        city: "Dhaka",
        area: "Dhanmondi",
        averageRating: "4.96",
        totalReviews: 184,
        completedJobs: 512,
        hourlyRate: "850",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-p2",
        name: "Rubel Miah",
        avatar: null,
        professionalTitle: "Pipe fitting specialist",
        city: "Dhaka",
        area: "Mirpur",
        averageRating: "4.88",
        totalReviews: 141,
        completedJobs: 398,
        hourlyRate: "720",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-p3",
        name: "Sohel Rana",
        avatar: null,
        professionalTitle: "Sanitary installer",
        city: "Chattogram",
        area: "Agrabad",
        averageRating: "4.81",
        totalReviews: 97,
        completedJobs: 286,
        hourlyRate: "640",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-p4",
        name: "Jahid Hasan",
        avatar: null,
        professionalTitle: "Geyser technician",
        city: "Dhaka",
        area: "Uttara",
        averageRating: "4.77",
        totalReviews: 83,
        completedJobs: 231,
        hourlyRate: "700",
        isFeatured: false,
        isAvailable: false,
      },
      {
        id: "tech-p5",
        name: "Faruk Ahmed",
        avatar: null,
        professionalTitle: "Drainage specialist",
        city: "Sylhet",
        area: "Zindabazar",
        averageRating: "4.72",
        totalReviews: 64,
        completedJobs: 175,
        hourlyRate: "580",
        isFeatured: false,
        isAvailable: true,
      },
    ],
    topServices: [
      {
        id: "svc-p1",
        title: "Emergency leak repair",
        technicianId: "tech-p1",
        technicianName: "Karim Mia",
        price: "1200",
        estimatedDuration: 90,
        totalBookings: 312,
      },
      {
        id: "svc-p2",
        title: "Drain unblocking with camera check",
        technicianId: "tech-p5",
        technicianName: "Faruk Ahmed",
        price: "950",
        estimatedDuration: 75,
        totalBookings: 268,
      },
      {
        id: "svc-p3",
        title: "Geyser installation",
        technicianId: "tech-p4",
        technicianName: "Jahid Hasan",
        price: "2100",
        estimatedDuration: 150,
        totalBookings: 141,
      },
      {
        id: "svc-p4",
        title: "Full bathroom fitting",
        technicianId: "tech-p2",
        technicianName: "Rubel Miah",
        price: "2500",
        estimatedDuration: 240,
        totalBookings: 96,
      },
    ],
  },

  electrical: {
    ...CATEGORY_LIST[1],
    coverImage: photo(PANEL, "&w=2400"),
    tagline: "Licensed hands on every live wire.",
    overview: [
      "Electrical work is the one category where we refuse an application outright without a trade licence on file. Every profile here has been through that check, and an admin can pull it the moment a complaint stands up.",
      "Quotes cover labour and standard fittings. Anything beyond that is priced in front of you before the work starts, never added at the door.",
    ],
    completedJobs: 3620,
    responseMinutes: 38,
    priceRange: { min: "500", max: "3200" },
    commonIssues: [
      "Circuit tripping the moment it loads",
      "Dead sockets on one wall",
      "Flickering or humming lights",
      "Distribution board past its life",
      "New points for an appliance",
      "Burning smell from a switch",
    ],
    topTechnicians: [
      {
        id: "tech-e1",
        name: "Nasir Uddin",
        avatar: null,
        professionalTitle: "Licensed electrician",
        city: "Dhaka",
        area: "Banani",
        averageRating: "4.94",
        totalReviews: 203,
        completedJobs: 604,
        hourlyRate: "900",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-e2",
        name: "Imran Kabir",
        avatar: null,
        professionalTitle: "Panel and board specialist",
        city: "Dhaka",
        area: "Gulshan",
        averageRating: "4.9",
        totalReviews: 158,
        completedJobs: 441,
        hourlyRate: "980",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-e3",
        name: "Shafiq Islam",
        avatar: null,
        professionalTitle: "Domestic wiring",
        city: "Gazipur",
        area: "Tongi",
        averageRating: "4.85",
        totalReviews: 112,
        completedJobs: 322,
        hourlyRate: "700",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-e4",
        name: "Rafiqul Alam",
        avatar: null,
        professionalTitle: "Lighting installer",
        city: "Chattogram",
        area: "Khulshi",
        averageRating: "4.8",
        totalReviews: 89,
        completedJobs: 245,
        hourlyRate: "650",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-e5",
        name: "Babul Hossain",
        avatar: null,
        professionalTitle: "Fault finding",
        city: "Dhaka",
        area: "Mohammadpur",
        averageRating: "4.75",
        totalReviews: 71,
        completedJobs: 198,
        hourlyRate: "620",
        isFeatured: false,
        isAvailable: false,
      },
    ],
    topServices: [
      {
        id: "svc-e1",
        title: "Tripping circuit diagnosis",
        technicianId: "tech-e5",
        technicianName: "Babul Hossain",
        price: "900",
        estimatedDuration: 60,
        totalBookings: 341,
      },
      {
        id: "svc-e2",
        title: "Distribution board upgrade",
        technicianId: "tech-e2",
        technicianName: "Imran Kabir",
        price: "3200",
        estimatedDuration: 210,
        totalBookings: 128,
      },
      {
        id: "svc-e3",
        title: "New socket or light point",
        technicianId: "tech-e3",
        technicianName: "Shafiq Islam",
        price: "700",
        estimatedDuration: 45,
        totalBookings: 289,
      },
      {
        id: "svc-e4",
        title: "Full flat rewiring survey",
        technicianId: "tech-e1",
        technicianName: "Nasir Uddin",
        price: "1500",
        estimatedDuration: 120,
        totalBookings: 74,
      },
    ],
  },

  "ac-cooling": {
    ...CATEGORY_LIST[2],
    coverImage: photo(BENCH, "&w=2400&bri=-18"),
    tagline: "Cold air back before the afternoon.",
    overview: [
      "Cooling is seasonal and the queue moves fast, so this category shows live availability first. A technician marked as accepting work has hours published for the next seven days.",
      "Servicing includes a filter clean and a gas pressure check. If a top-up is needed the price is confirmed on the call, not after the panel is open.",
    ],
    completedJobs: 2740,
    responseMinutes: 51,
    priceRange: { min: "800", max: "4500" },
    commonIssues: [
      "Unit runs but does not cool",
      "Water dripping from the indoor unit",
      "Gas pressure low after a season",
      "Loud rattle from the outdoor fan",
      "New split unit installation",
      "Remote or thermostat not responding",
    ],
    topTechnicians: [
      {
        id: "tech-a1",
        name: "Tanvir Ahmed",
        avatar: null,
        professionalTitle: "HVAC technician",
        city: "Dhaka",
        area: "Bashundhara",
        averageRating: "4.89",
        totalReviews: 176,
        completedJobs: 488,
        hourlyRate: "950",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-a2",
        name: "Mizanur Rahman",
        avatar: null,
        professionalTitle: "Split unit installer",
        city: "Dhaka",
        area: "Badda",
        averageRating: "4.82",
        totalReviews: 134,
        completedJobs: 371,
        hourlyRate: "870",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-a3",
        name: "Habibur Rashid",
        avatar: null,
        professionalTitle: "Refrigeration engineer",
        city: "Chattogram",
        area: "Nasirabad",
        averageRating: "4.78",
        totalReviews: 101,
        completedJobs: 279,
        hourlyRate: "800",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-a4",
        name: "Selim Reza",
        avatar: null,
        professionalTitle: "Servicing specialist",
        city: "Narayanganj",
        area: "Fatullah",
        averageRating: "4.71",
        totalReviews: 78,
        completedJobs: 214,
        hourlyRate: "740",
        isFeatured: false,
        isAvailable: false,
      },
      {
        id: "tech-a5",
        name: "Arif Chowdhury",
        avatar: null,
        professionalTitle: "Ducting and vents",
        city: "Dhaka",
        area: "Motijheel",
        averageRating: "4.66",
        totalReviews: 59,
        completedJobs: 168,
        hourlyRate: "690",
        isFeatured: false,
        isAvailable: true,
      },
    ],
    topServices: [
      {
        id: "svc-a1",
        title: "Split AC full servicing",
        technicianId: "tech-a4",
        technicianName: "Selim Reza",
        price: "1400",
        estimatedDuration: 90,
        totalBookings: 402,
      },
      {
        id: "svc-a2",
        title: "Gas refill with leak test",
        technicianId: "tech-a1",
        technicianName: "Tanvir Ahmed",
        price: "2600",
        estimatedDuration: 120,
        totalBookings: 217,
      },
      {
        id: "svc-a3",
        title: "New unit installation",
        technicianId: "tech-a2",
        technicianName: "Mizanur Rahman",
        price: "4500",
        estimatedDuration: 240,
        totalBookings: 133,
      },
      {
        id: "svc-a4",
        title: "Drain line unclog",
        technicianId: "tech-a3",
        technicianName: "Habibur Rashid",
        price: "800",
        estimatedDuration: 45,
        totalBookings: 186,
      },
    ],
  },

  "appliance-repair": {
    ...CATEGORY_LIST[3],
    coverImage: photo(BENCH, "&w=2400&bri=-32&sat=-10"),
    tagline: "Your kitchen back in service the same day.",
    overview: [
      "Appliance jobs are diagnosed on the first visit and quoted before a part is ordered. If the repair is not worth the money, the technician is expected to say so.",
      "Work carries a 30-day warranty. Raise a fault inside that window and the return visit costs nothing.",
    ],
    completedJobs: 2980,
    responseMinutes: 47,
    priceRange: { min: "600", max: "3800" },
    commonIssues: [
      "Fridge cooling on one side only",
      "Washing machine not draining",
      "Oven heating unevenly",
      "Microwave sparking inside",
      "Dishwasher leaving residue",
      "Compressor running constantly",
    ],
    topTechnicians: [
      {
        id: "tech-r1",
        name: "Delwar Hossain",
        avatar: null,
        professionalTitle: "Appliance engineer",
        city: "Dhaka",
        area: "Shantinagar",
        averageRating: "4.86",
        totalReviews: 165,
        completedJobs: 452,
        hourlyRate: "820",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-r2",
        name: "Kamal Uddin",
        avatar: null,
        professionalTitle: "Refrigeration repair",
        city: "Dhaka",
        area: "Malibagh",
        averageRating: "4.79",
        totalReviews: 128,
        completedJobs: 356,
        hourlyRate: "760",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-r3",
        name: "Anwar Sadat",
        avatar: null,
        professionalTitle: "Washing machine specialist",
        city: "Khulna",
        area: "Sonadanga",
        averageRating: "4.73",
        totalReviews: 94,
        completedJobs: 261,
        hourlyRate: "690",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-r4",
        name: "Masud Parvez",
        avatar: null,
        professionalTitle: "Oven and hob repair",
        city: "Dhaka",
        area: "Rampura",
        averageRating: "4.68",
        totalReviews: 72,
        completedJobs: 203,
        hourlyRate: "650",
        isFeatured: false,
        isAvailable: false,
      },
      {
        id: "tech-r5",
        name: "Liton Sarker",
        avatar: null,
        professionalTitle: "Small appliance repair",
        city: "Rajshahi",
        area: "Boalia",
        averageRating: "4.61",
        totalReviews: 51,
        completedJobs: 147,
        hourlyRate: "600",
        isFeatured: false,
        isAvailable: true,
      },
    ],
    topServices: [
      {
        id: "svc-r1",
        title: "Fridge cooling repair",
        technicianId: "tech-r2",
        technicianName: "Kamal Uddin",
        price: "1800",
        estimatedDuration: 120,
        totalBookings: 294,
      },
      {
        id: "svc-r2",
        title: "Washing machine drain fix",
        technicianId: "tech-r3",
        technicianName: "Anwar Sadat",
        price: "1100",
        estimatedDuration: 75,
        totalBookings: 246,
      },
      {
        id: "svc-r3",
        title: "Oven element replacement",
        technicianId: "tech-r4",
        technicianName: "Masud Parvez",
        price: "1600",
        estimatedDuration: 90,
        totalBookings: 132,
      },
      {
        id: "svc-r4",
        title: "Compressor replacement",
        technicianId: "tech-r1",
        technicianName: "Delwar Hossain",
        price: "3800",
        estimatedDuration: 180,
        totalBookings: 68,
      },
    ],
  },

  carpentry: {
    ...CATEGORY_LIST[4],
    coverImage: photo(TIMBER, "&w=2400&bri=-28&sat=-10"),
    tagline: "Millimetre work, not rough guesses.",
    overview: [
      "Carpentry jobs are quoted by the piece, not the hour, so a wardrobe that takes longer than planned costs you the same. The measurement visit is free inside the technician's service radius.",
      "Every carpenter listed brings their own tools and clears the offcuts before leaving. That is part of the job, not an extra line.",
    ],
    completedJobs: 1860,
    responseMinutes: 63,
    priceRange: { min: "700", max: "5200" },
    commonIssues: [
      "Door not closing or dropping on its hinges",
      "Cabinet doors out of alignment",
      "TV or shelf mounting on concrete",
      "Drawer runners worn out",
      "Custom wardrobe fitting",
      "Window frame swollen or stuck",
    ],
    topTechnicians: [
      {
        id: "tech-c1",
        name: "Abdul Malek",
        avatar: null,
        professionalTitle: "Master carpenter",
        city: "Dhaka",
        area: "Mohakhali",
        averageRating: "4.92",
        totalReviews: 147,
        completedJobs: 386,
        hourlyRate: "880",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-c2",
        name: "Ripon Das",
        avatar: null,
        professionalTitle: "Furniture maker",
        city: "Dhaka",
        area: "Jatrabari",
        averageRating: "4.84",
        totalReviews: 109,
        completedJobs: 298,
        hourlyRate: "800",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-c3",
        name: "Shamim Reza",
        avatar: null,
        professionalTitle: "Door and window fitting",
        city: "Comilla",
        area: "Kandirpar",
        averageRating: "4.77",
        totalReviews: 86,
        completedJobs: 231,
        hourlyRate: "720",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-c4",
        name: "Nurul Amin",
        avatar: null,
        professionalTitle: "Cabinet installer",
        city: "Dhaka",
        area: "Kallyanpur",
        averageRating: "4.7",
        totalReviews: 63,
        completedJobs: 179,
        hourlyRate: "700",
        isFeatured: false,
        isAvailable: false,
      },
      {
        id: "tech-c5",
        name: "Jasim Uddin",
        avatar: null,
        professionalTitle: "Mounting and fixtures",
        city: "Barishal",
        area: "Band Road",
        averageRating: "4.64",
        totalReviews: 48,
        completedJobs: 134,
        hourlyRate: "640",
        isFeatured: false,
        isAvailable: true,
      },
    ],
    topServices: [
      {
        id: "svc-c1",
        title: "Door repair and realignment",
        technicianId: "tech-c3",
        technicianName: "Shamim Reza",
        price: "1300",
        estimatedDuration: 90,
        totalBookings: 218,
      },
      {
        id: "svc-c2",
        title: "TV wall mounting",
        technicianId: "tech-c5",
        technicianName: "Jasim Uddin",
        price: "900",
        estimatedDuration: 60,
        totalBookings: 264,
      },
      {
        id: "svc-c3",
        title: "Kitchen cabinet fitting",
        technicianId: "tech-c4",
        technicianName: "Nurul Amin",
        price: "3400",
        estimatedDuration: 300,
        totalBookings: 87,
      },
      {
        id: "svc-c4",
        title: "Custom wardrobe build",
        technicianId: "tech-c1",
        technicianName: "Abdul Malek",
        price: "5200",
        estimatedDuration: 480,
        totalBookings: 41,
      },
    ],
  },

  painting: {
    ...CATEGORY_LIST[5],
    coverImage: photo(TIMBER, "&w=2400&sat=-40&bri=10"),
    tagline: "Prep first. That is where the finish comes from.",
    overview: [
      "Painting is quoted by room and coat, with surface prep included. Filler, sanding and masking are part of the price, not a separate visit.",
      "Furniture is sheeted and the room is put back before the technician leaves. Paint is bought against your brand choice and itemised on the invoice.",
    ],
    completedJobs: 1240,
    responseMinutes: 74,
    priceRange: { min: "1200", max: "8000" },
    commonIssues: [
      "Damp patches showing through the coat",
      "Peeling paint on an exterior wall",
      "Full room repaint before moving in",
      "Ceiling stained after a leak",
      "Grille and railing repaint",
      "Wall cracks needing filler first",
    ],
    topTechnicians: [
      {
        id: "tech-n1",
        name: "Sumon Mia",
        avatar: null,
        professionalTitle: "Painting contractor",
        city: "Dhaka",
        area: "Lalmatia",
        averageRating: "4.81",
        totalReviews: 96,
        completedJobs: 264,
        hourlyRate: "700",
        isFeatured: true,
        isAvailable: true,
      },
      {
        id: "tech-n2",
        name: "Rasel Khan",
        avatar: null,
        professionalTitle: "Interior finisher",
        city: "Dhaka",
        area: "Khilgaon",
        averageRating: "4.74",
        totalReviews: 74,
        completedJobs: 201,
        hourlyRate: "660",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-n3",
        name: "Alamgir Hossain",
        avatar: null,
        professionalTitle: "Exterior coating",
        city: "Chattogram",
        area: "Halishahar",
        averageRating: "4.69",
        totalReviews: 58,
        completedJobs: 163,
        hourlyRate: "640",
        isFeatured: false,
        isAvailable: true,
      },
      {
        id: "tech-n4",
        name: "Bashir Ahmed",
        avatar: null,
        professionalTitle: "Damp and crack repair",
        city: "Mymensingh",
        area: "Ganginar Par",
        averageRating: "4.62",
        totalReviews: 44,
        completedJobs: 121,
        hourlyRate: "600",
        isFeatured: false,
        isAvailable: false,
      },
      {
        id: "tech-n5",
        name: "Milon Sheikh",
        avatar: null,
        professionalTitle: "Decorative finishes",
        city: "Rangpur",
        area: "Jahaj Company",
        averageRating: "4.55",
        totalReviews: 31,
        completedJobs: 88,
        hourlyRate: "580",
        isFeatured: false,
        isAvailable: true,
      },
    ],
    topServices: [
      {
        id: "svc-n1",
        title: "Single room repaint",
        technicianId: "tech-n2",
        technicianName: "Rasel Khan",
        price: "4200",
        estimatedDuration: 360,
        totalBookings: 154,
      },
      {
        id: "svc-n2",
        title: "Damp patch treatment",
        technicianId: "tech-n4",
        technicianName: "Bashir Ahmed",
        price: "1800",
        estimatedDuration: 120,
        totalBookings: 118,
      },
      {
        id: "svc-n3",
        title: "Exterior wall coating",
        technicianId: "tech-n3",
        technicianName: "Alamgir Hossain",
        price: "8000",
        estimatedDuration: 600,
        totalBookings: 46,
      },
      {
        id: "svc-n4",
        title: "Ceiling touch-up",
        technicianId: "tech-n1",
        technicianName: "Sumon Mia",
        price: "1200",
        estimatedDuration: 90,
        totalBookings: 132,
      },
    ],
  },
};
